import type { NextPage } from "next";
import Head from "next/head";
import { Bookmark } from "../components/Bookmark";

const URL_LIST = [
  "https://beta.reactjs.org/learn/state-as-a-snapshot",
  "https://beta.reactjs.org/learn/state-as-a-snapshot",
  // "https://www.fukuoka-airport.jp/",
  "https://通信エラーが起きてほしいな.com",
];

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Notion Style Bookmark Component</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="overflow-y-scroll p-12 m-auto max-w-screen-md h-screen">
        <div className="h-full">
          {URL_LIST.map((url, i) => (
            <>
              <Bookmark url={url} key={i.toString()} />
              <div className="h-4"></div>
            </>
          ))}
        </div>
      </main>
    </div>
  );
};

export default Home;
