import type { NextPage } from "next";
import Head from "next/head";
import { BookmarkView } from "../components/Bookmark";
import { mockOgpDataList } from "../mocks";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Notion Style Bookmark Component</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col justify-evenly p-2 mx-auto max-w-2xl h-screen">
        {mockOgpDataList.map((ogp) => (
          <BookmarkView ogp={ogp} key={ogp.title} />
        ))}
      </main>
    </div>
  );
};

export default Home;
